# See https://github.com/realm/SwiftLint/blob/master/Rules.md for details on rules.
# See https://medium.com/developermind/using-swiftlint-and-danger-for-swift-best-practices-48432e4e268a for in-file comments, etc.

disabled_rules:  # I don't want these
  - deployment_target
  - empty_parentheses_with_trailing_closure
  - file_length
  - force_cast
  - force_try
  - identifier_name
  - line_length
  - no_fallthrough_only
  - private_over_fileprivate
  - return_arrow_whitespace
  - todo
  - trailing_whitespace
  - type_name
  - vertical_whitespace

opt_in_rules:  # I really want these
  - array_init
  - closure_spacing
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - fatal_error_message
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_function_chains
## - untyped_error_in_catch  # Maybe I'll turn this on when I'm ready.
  - unused_import
  - yoda_condition

excluded:  # paths to ignore during linting.
  - ItemEncryptTests/
  - IDZSwiftCommonCrypto/

included:
  - ~/Desktop/XCode/HandyHelpers/HandyHelpers/CoreHelper/Core/CoreDataStack.swift
  - ./

cyclomatic_complexity: 13
empty_count: warning
force_cast: warning
force_try: warning
line_length: 150
type_body_length:
  warning: 400
  error: 1000
